spring:
  application:
    name: food-ordering-system

  # Database Config
  datasource:
    # CHANGE 5432 -> 5435
    url: jdbc:postgresql://localhost:5435/food_ordering_db
    username: food_user
    password: food_pass
    driver-class-name: org.postgresql.Driver

  # JPA / Hibernate
  jpa:
    hibernate:
      ddl-auto: update # In production, use "validate" + Flyway
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  # Redis Config
  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8080